### ISSUE TITLE
Storing configuration data in extern file with a common file type

### ISSUE THREAD

**Issue by schiederme** [Jugendhackt/ShitHub#1]
Hey, 
do you want an PR with .env files for config?

Max

**Comment by luap42** [comment]
Why not using `cnf` or `cfg`? They seem to be defined as Configuration files (standard) <https://en.wikipedia.org/wiki/List_of_filename_extensions_(A%E2%80%93E)#E>

**Comment by luap42** [comment]
I would use the JSON format for storing data.

**Comment by luap42** [comment]
Added an PR. #2

**Comment by schiederme** [comment]
PLEASE: Let the issues open until the creator can answer to questions. Its very contra productive.

**Comment by anghenfil** [comment]
I totally agree with you MaximilianSchieder.

**Comment by schiederme** [comment]
.env is already used in much projects including laravel. This should be much better then re invent the wheel. Or I' m wrong?

**Comment by luap42** [comment]
Hello, I have just created a .env file under my Apache XAMPP installation root and were able to show it via localhost/.env. So I do not suppose that this type is more secure than my proposal. AFAIK Apache only hides .ht* files.

**Comment by anghenfil** [comment]
Edit 3: You must move the .env file out of your webroot. Then, phpdotenv can load the settings.

**Comment by anghenfil** [comment]
I will create a new pull request and implement phpdotenv

**Comment by anghenfil** [comment]
See Pull Request #4

**Comment by luap42** [comment]
Pull Request #4 has been merged (Edit anghenfil: after internal disscussion and decision). Closing this Issue
