### ISSUE TITLE
how to install it ???

### ISSUE THREAD

**Issue by alidz1982** [Jugendhackt/ShitHub#7]

**Comment by anghenfil** [comment]
Hello,
here is a short installation instruction:

1. Install a webserver (with php 7) and mysql database as development system
(https://www.howtoforge.com/tutorial/install-apache-with-php-and-mysql-on-ubuntu-16-04-lamp/#-install-php-)
2. Copy the config.env.example to any location outside your webroot and rename to config.env
3. Enter the config path in index.php

**Comment by alidz1982** [comment]
thanks..i will try it

**Comment by anghenfil** [comment]
Additionally, you will need to create the mysql strucutre. Have a look at our wiki.

**Comment by anghenfil** [comment]
Hi, we created an installation script. (see #9 )
